configuration: Release

before_build:
- cd src
- nuget restore
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image: Visual Studio 2019

build:
  verbosity: minimal
